HipHopZen/Controllers/CategoryController.cs
using HipHopZen.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HipHopZen.Controllers
{
    public class CategoryController : Controller
    {
        ApplicationDbContext context;

        public CategoryController()
        {
            context = new ApplicationDbContext();
        }

        // GET: Category
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Show()
        {
            return View("Show");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(Category model)
        {
            Category category = new Category(model.Name);
            context.Categories.Add(category);
            context.SaveChanges();
            return RedirectToAction("Show");
        }

        public ActionResult CategoryList()
        {
            var categories = from c in context.Categories
                             orderby c.Name ascending
                             select c;
            return PartialView("_CategoryList", categories);
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            Category category = context.Categories.Find(id);
            var posts = from p in context.Posts
                        where p.CategoryID == id
                        select p;
            Category other = (from c in context.Categories
                              where c.Name == "Other"
                              select c).FirstOrDefault();
            foreach (Post p in posts)
            {
                p.CategoryID = other.Id;
                p.Category = other;
            }

            context.Categories.Remove(category);
            context.SaveChanges();
            return RedirectToAction("CategoryList");
        }

        public ActionResult SearchByCategory(string category)
        {
            var posts = from p in context.Posts
                        where p.Category.Name == category
                        orderby p.Date descending
                        select new PostDetailsModel
                        {
                            Id = p.Id,
                            Title = p.Title,
                            Description = p.Description,
                            Date = p.Date,
                            Votes = p.Votes,
                            Rating = p.Rating,
                            Price = p.Price,
                            URL = p.URL,
                            PhotoFile = p.PhotoFile,
                            ImageMimeType = p.ImageMimeType,
                            VideoURL = p.VideoURL,
                            UserName = p.User.Name,
                            CategoryName = p.Category.Name,
                            Comments = p.Comments
                        };
            if (string.IsNullOrEmpty(category) || string.IsNullOrWhiteSpace(category))
            {
                ViewBag.Category = null;
                ViewBag.Total = 0;
            }
            else
            {
                ViewBag.Category = category;
                ViewBag.Total = posts.Count();
            }
            return View("SearchByCategory", posts);
        }
    }
}

HipHopZen/Controllers/CommentController.cs
using HipHopZen.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HipHopZen.Controllers
{
    public class CommentController : Controller
    {
        ApplicationDbContext context;

        public CommentController()
        {
            context = new ApplicationDbContext();
        }

        // GET: Comment
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult _Create(int postId)
        {
            Comment comment = new Comment();
            comment.PostID = postId;

            ViewBag.PostId = postId;
            return PartialView("_CreateAComment");
        }

        // GET: Action which return PartialView for displaying the comments of a given Post
        [ChildActionOnly]   //The action cannot be accessed from the browser's address bar
        public PartialViewResult _CommentsForPost(int postId)
        {
            var comments = from c in context.Comments
                           where c.PostID == postId
                           select c;

            ViewBag.PostId = postId;
            return PartialView("_CommentsForPost", comments.ToList());
        }

        //POST: Action which saves and shows a comment when the AJAX comment create tool is used
        [HttpPost]
        public PartialViewResult _CommentsForPost(Comment comment, int postId)
        {
            context.Comments.Add(comment);  //Save the comment in the database
            context.SaveChanges();

            var comments = from c in context.Comments   //Get the updated list of comments
                           where c.PostID == postId
                           select c;

            ViewBag.PostId = postId;
            return PartialView("_ShowComments", comments.ToList());
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            Comment comment = context.Comments.Find(id);
            if(comment == null)
            {
                return HttpNotFound();
            }
            int postId = comment.PostID;
            context.Comments.Remove(comment);
            context.SaveChanges();

            var comments = from c in context.Comments   //Get the updated list of comments
                           where c.PostID == postId
                           select c;

            ViewBag.PostId = postId;
            return PartialView("_ShowComments", comments.ToList());
        }
    }
}

HipHopZen/Controllers/PostController.cs
using HipHopZen.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HipHopZen.Controllers
{
    [HandleError(View = "Error")]
    public class PostController : Controller
    {
        private ApplicationDbContext context;

        public PostController()
        {
            context = new ApplicationDbContext();
        }

        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult Show()
        {
            return View("Show");
        }

        [Authorize]
        public ActionResult PostList()
        {
            var posts = from p in context.Posts
                        orderby p.Date descending
                        select new PostDetailsModel()
                        {
                            Id = p.Id,
                            Title = p.Title,
                            Description = p.Description,
                            Date = p.Date,
                            Votes = p.Votes,
                            Rating = p.Rating,
                            Price = p.Price,
                            URL = p.URL,
                            PhotoFile = p.PhotoFile,
                            ImageMimeType = p.ImageMimeType,
                            VideoURL = p.VideoURL,
                            CategoryName = p.Category.Name,
                        };
            return PartialView("_PostList", posts);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create()
        {
            List<string> categories = new List<string>();
            foreach (Category c in context.Categories.ToList())
            {
                categories.Add(c.Name);
            }

            ViewBag.Categories = new SelectList(categories);
            return View("Create");
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(Post model, HttpPostedFileBase image)
        {
            if (model != null && this.ModelState.IsValid)
            {
                Category category = (from c in context.Categories
                                     where c.Name == model.Category.Name
                                     select c).FirstOrDefault();
                if (category != null && image != null)
                {
                    Post post = new Post()
                    {
                        Title = model.Title,
                        Description = model.Description,
                        Date = DateTime.Today,
                        Votes = 0,
                        Rating = model.Rating,
                        Price = model.Price,
                        URL = model.URL,
                        PhotoFile = new byte[image.ContentLength],
                        ImageMimeType = image.ContentType,
                        VideoURL = model.VideoURL,
                        UserID = User.Identity.GetUserId(),
                        CategoryID = category.Id,
                        Category = category,
                        Comments = new List<Comment>()
                    };
                    image.InputStream.Read(post.PhotoFile, 0, image.ContentLength);
                    context.Posts.Add(post);
                    context.SaveChanges();
                }
                return RedirectToAction("Show");
            }
            return View(model);
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            Post post = context.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            context.Posts.Remove(post);
            context.SaveChanges();
            return RedirectToAction("PostList");
        }


        [HttpGet]
        [Authorize]
        public ActionResult Edit(int id)
        {
            var posts = from p in context.Posts
                        where p.Id == id
                        select new PostEditModel
                        {
                            Id = p.Id,
                            Title = p.Title,
                            Description = p.Description,
                            Rating = p.Rating,
                            Price = p.Price,
                            URL = p.URL,
                            PhotoFile = p.PhotoFile,
                            ImageMimeType = p.ImageMimeType,
                            VideoURL = p.VideoURL,
                            CategoryName = p.Category.Name
                        };
            return View("Edit", posts.FirstOrDefault());
        }

        [HttpPost]
        [Authorize]
        public ActionResult Edit(PostEditModel model, HttpPostedFileBase image)
        {
            if (model != null && this.ModelState.IsValid)
            {
                Post post = context.Posts.Find(model.Id);
                post.Title = model.Title;
                post.Description = model.Description;
                post.Rating = model.Rating;
                post.Price = model.Price;
                post.URL = model.URL;
                post.VideoURL = model.VideoURL;
                if (image != null)
                {
                    post.PhotoFile = new byte[image.ContentLength];
                    post.ImageMimeType = image.ContentType;
                    image.InputStream.Read(post.PhotoFile, 0, image.ContentLength);
                }

                Category category = (from c in context.Categories
                                     where c.Name == model.CategoryName
                                     select c).FirstOrDefault();
                post.CategoryID = category.Id;
                post.Category = category;
                context.SaveChanges();

                return RedirectToAction("Show");
            }
            return View("Edit", model);
        }

        public ActionResult Details(int id)
        {
            var post = from p in context.Posts
                       where p.Id == id
                       select new PostDetailsModel
                       {
                           Id = p.Id,
                           Title = p.Title,
                           Description = p.Description,
                           Date = p.Date,
                           Votes = p.Votes,
                           Rating = p.Rating,
                           Price = p.Price,
                           URL = p.URL,
                           PhotoFile = p.PhotoFile,
                           ImageMimeType = p.ImageMimeType,
                           VideoURL = p.VideoURL,
                           UserName = p.User.Name,
                           CategoryName = p.Category.Name,
                           Comments = p.Comments
                       };
            return View("Details", post.FirstOrDefault());
        }

        public ActionResult AddVote(int id)
        {
            Post post = (from p in context.Posts
                         where p.Id == id
                         select p).FirstOrDefault();
            post.Votes += 1;
            context.SaveChanges();

            return PartialView("_Votes", post);
        }

        public ActionResult SearchByCategory(string category)
        {
            var posts = from p in context.Posts
                        where p.Category.Name == category
                        orderby p.Date descending
                        select new PostDetailsModel
                        {
                            Id = p.Id,
                            Title = p.Title,
                            Description = p.Description,
                            Date = p.Date,
                            Votes = p.Votes,
                            Rating = p.Rating,
                            Price = p.Price,
                            URL = p.URL,
                            PhotoFile = p.PhotoFile,
                            ImageMimeType = p.ImageMimeType,
                            VideoURL = p.VideoURL,
                            UserName = p.User.Name,
                            CategoryName = p.Category.Name,
                            Comments = p.Comments
                        };
            if (string.IsNullOrEmpty(category) || string.IsNullOrWhiteSpace(category))
            {
                ViewBag.Category = null;
                ViewBag.Total = 0;
            }
            else
            {
                ViewBag.Category = category;
                ViewBag.Total = posts.Count();
            }
            return View("SearchByCategory", posts);
        }

        public ActionResult GetCategories()
        {
            List<string> categories = new List<string>();
            foreach (Category c in context.Categories.ToList())
            {
                categories.Add(c.Name);
            }
            return Json(categories, JsonRequestBehavior.AllowGet);
        }

        public FileContentResult GetImage(int id)
        {
            Post post = context.Posts.Find(id);
            if (post.PhotoFile != null)
            {
                return File(post.PhotoFile, post.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

HipHopZen/Views/Shared/_CommentsForPost.cshtml
@model IEnumerable<HipHopZen.Models.Comment>

<h4>Comments:</h4>
<div id="comments-tool">
    @foreach (var item in Model)
    {
        <div class="panel panel-info" id="commentList">
            <div class="panel-heading">
                <strong>@item.Nickname:</strong>
                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <button type="button" data-delete-confirmation-text='Do you want to delete this comment: @item.Text?' data-delete-url="@Url.Action("Delete", "Comment", new { id = item.Id })" class="btn btn-sm btn-danger glyphicon glyphicon-remove pull-right"></button>
                }
            </div>
            <div class="panel-body">
                @Html.DisplayFor(modelItem => item.Text)
                <br />
                <small><em>@Html.DisplayFor(modelItem => item.Date)</em></small>
            </div>
        </div>
    }
</div>
<div id="addcomment" class="add-comment-box">
    @Html.Action("_Create", "Comment", new { postId = ViewBag.PostId })
</div>

HipHopZen/Views/Shared/_CreateAComment.cshtml
@model HipHopZen.Models.Comment

@using (Ajax.BeginForm("_CommentsForPost",
                                   "Comment",
                                   new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "comments-tool" }))
{
    <div class="add-comment-tool">
        @Html.HiddenFor(m => m.PostID)
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nickname, new { htmlAttributes = new { @class = "form-control", placeholder = "Create a nickname" } })
                @Html.ValidationMessageFor(model => model.Nickname, "", new { @class = "text-danger" })
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control", placeholder = "Add a comment" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10" style="margin-top: 5px;">
                <input type="submit" value="Create" class="btn btn-default" />
                <input type="reset" value="Cancel" class="btn btn-default" />
            </div>
        </div>
    </div>
}

HipHopZen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type='text/javascript'>
        var appInsights = window.appInsights || function (config) {
            function r(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } }
            var t = { config: config }, u = document, e = window, o = 'script', s = u.createElement(o), i, f; for (s.src = config.url || '//az416426.vo.msecnd.net/scripts/a/ai.0.js', u.getElementsByTagName(o)[0].parentNode.appendChild(s), t.cookie = u.cookie, t.queue = [], i = ['Event', 'Exception', 'Metric', 'PageView', 'Trace', 'Ajax']; i.length;) r('track' + i.pop()); return r('setAuthenticatedUserContext'), r('clearAuthenticatedUserContext'), config.disableExceptionTracking || (i = 'onerror', r('_' + i), f = e[i], e[i] = function (config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o), s }), t
        }({
            instrumentationKey: 'd8c0311d-0804-46e7-b0cd-1a80b76010e8'
        });

        window.appInsights = appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Create post", "Create", "Post")</li>
                        <li>@Html.ActionLink("Manage posts", "Show", "Post")</li>
                    }
                    <li>@Html.ActionLink("Categories", "Show", "Category")</li>
                    <li>@Html.ActionLink("About us", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact us", "Contact", "Home")</li>
                    <li>
                        @using (Html.BeginForm("SearchByCategory", "Post", FormMethod.Get, new { @class = "search-form" }))
                        {
                            <input type="text" class="form-control searchbar" placeholder="Search by category" name="category">
                            <button type="submit" class="btn btn-primary btn-search" style="display: inline">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        }
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="panel-footer">
            <p>
                <div class="text-info">
                    <span class="text-success">Created by:</span><br />
                    Alek Petreski
                </div>
            </p>
            <p>
                @DateTime.Now.Year &copy;<br />
                Hip-Hop Zen
            </p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/ajax")
    @RenderSection("scripts", required: false)
</body>
</html>

HipHopZen/Views/Shared/_ShowComments.cshtml
@model IEnumerable<HipHopZen.Models.Comment>

@foreach (var item in Model)
{
    <div class="panel panel-info" id="commentList">
        <div class="panel-heading">
            <strong>@item.Nickname:</strong>
            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {
                <button type="button" data-delete-confirmation-text='Do you want to delete this comment: @item.Text?' data-delete-url="@Url.Action("Delete", "Comment", new { id = item.Id })" class="btn btn-sm btn-danger glyphicon glyphicon-remove pull-right"></button>
            }
        </div>
        <div class="panel-body">
            @Html.DisplayFor(modelItem => item.Text)
            <br />
            <small><em>@Html.DisplayFor(modelItem => item.Date)</em></small>
        </div>
    </div>
}

HipHopZen/Views/Shared/_Votes.cshtml
@model HipHopZen.Models.Post

@Model.Votes