HipHopZen/Models/ApplicationUser.cs
using System.Data.Entity;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using System.ComponentModel;

namespace HipHopZen.Models
{
    public class ApplicationUser : IdentityUser
    {
        [StringLength(30)]
        [Required(ErrorMessage = "The Name field is required")]
        public string Name { get; set; }

        [StringLength(30)]
        [Required(ErrorMessage = "The Surname field is required")]
        public string Surname { get; set; }

        public ApplicationUser() { }

        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }
    }
}

HipHopZen/Controllers/ApplicationUserController.cs
using HipHopZen.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HipHopZen.Controllers
{
    [Authorize]
    public class ApplicationUserController : Controller
    {
        ApplicationDbContext context;

        public ApplicationUserController()
        {
            context = new ApplicationDbContext();
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Details(string id)
        {
            var user = from u in context.Users
                       where u.Id == id
                       select new ApplicationUserDetailsModel
                       {
                           Id = u.Id,
                           Name = u.Name,
                           Surname = u.Surname,
                           UserName = u.UserName,
                           Email = u.Email
                       };
            return View("Details", user.FirstOrDefault());
        }

        [HttpGet]
        public ActionResult Edit()
        {
            string id = User.Identity.GetUserId();
            var user = from u in context.Users
                       where u.Id == id
                       select new ApplicationUserEditModel
                       {
                           Id = u.Id,
                           Name = u.Name,
                           Surname = u.Surname,
                           UserName = u.UserName
                       };
            return View("Edit", user.FirstOrDefault());
        }

        [HttpPost]
        public ActionResult Edit(ApplicationUserEditModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                ApplicationUser user = context.Users.Find(User.Identity.GetUserId());
                user.Name = model.Name;
                user.Surname = model.Surname;
                user.UserName = model.UserName;
                context.SaveChanges();

                ApplicationUserDetailsModel userDetails = new ApplicationUserDetailsModel();
                userDetails.Id = user.Id;
                userDetails.Name = user.Name;
                userDetails.Surname = user.Surname;
                userDetails.UserName = user.UserName;
                userDetails.Email = user.Email;

                return RedirectToAction("Details", userDetails);
            }
            return View("Edit", model);
        }
    }
}

HipHopZen/Views/ApplicationUser/Details.cshtml
@model HipHopZen.Models.ApplicationUserDetailsModel
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Show user";
}

<h2>User: @Model.Name @Model.Surname</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>Name:</dt>
        <dd>@Model.Name</dd>

        <dt>Surname:</dt>
        <dd>@Model.Surname</dd>

        <dt>Username:</dt>
        <dd>@Model.UserName</dd>

        <dt>Email:</dt>
        <dd>@Model.Email</dd>
    </dl>
</div>
<br />

@if (Model.Id == User.Identity.GetUserId())
{
    <div class="links">
        @Html.ActionLink("Edit", "Edit") |
        @Html.ActionLink("Change your password", "ChangePassword", "Manage") |
        @Html.ActionLink("Home page", "Index", "Home")
    </div>
}
else
{
    <div class="links">
        @Html.ActionLink("Home page", "Index", "Home")
    </div>
}

HipHopZen/Views/ApplicationUser/Edit.cshtml
@model HipHopZen.Models.ApplicationUserEditModel
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Edit";
}

<h2>Edit your account</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                @Html.ActionLink("Cancel", "Details", "ApplicationUser", new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

<div class="links">
    @Html.ActionLink("Back to account", "Details", "ApplicationUser", new { id = User.Identity.GetUserId() }, new { @class = "something" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}